### ISSUE TITLE
New problems after last week

### ISSUE THREAD

**Issue by cigfairy** [excrupro/ThreateningYeti#28]
Using Respondus version 2.0.6.05 and Windows 10
I redownloaded Yetiloader yesterday.

With yetiloader, i can still do webcam check and follow pre-instructions.
However, when i click to start exam, yetiloader and respondus shut down and nothing happens.
Alt-tabbing and windows key still work. 
I have to logoff from windows and login again because taskbar is still missing.

Any idea how to fix the problem?

**Comment by melotic** [comment]
This is because they detect some of our hooks which I have fixed, but I haven't uploaded it to github. Get it on the build server [here ](https://ci.appveyor.com/project/sup3rvis0r/threateningyeti/builds/32486143/artifacts)and replace ThreateningYeti.dll with the one you just downloaded.

It appears that detection might only be used with Respondus Monitor.

**Comment by cigfairy** [comment]
it worked!!
much appreciated
