### ISSUE TITLE
Bypass the VM detection

### ISSUE THREAD

**Issue by zenof** [excrupro/ThreateningYeti#8]
Awesome works! And I am also thinking about does it possible to add a feature to bypass the VM detection:

![image](https://user-images.githubusercontent.com/37714471/77026769-7c385700-6962-11ea-974a-a8c8c9a3052d.png)

**Comment by melotic** [comment]
Will add support soon.

**Comment by dvl2014** [comment]
Any update if you macing mac version


Sent from Yahoo Mail for iPhone


On Wednesday, March 18, 2020, 11:36 PM, Justin <notifications@github.com> wrote:




Will add support soon.

**Comment by melotic** [comment]
I believe I've bypassed the VM detection. They could be detecting VMs somewhere else in the code. You can test the bypass with https://ci.appveyor.com/project/sup3rvis0r/threateningyeti/builds/31605940/artifacts . Replace the ThreateningYeti.dll with the one you downloaded there.

**Comment by zenof** [comment]
I just tested with the new ThreateningYeti.dll file and it works perfectly! Thanks for your great work!

**Comment by dvl2014** [comment]
Since you guys bypassed VM Detection, then there is no really need for mac version. I am somewhat new to GitHub but once I install a VM on my mac do I launch threateningYeti before I open the Lockdownbrowser link through chrome? Also is the threatening Yeti program the only program I need to install on my VM?
